name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # ✅ Use a stable version

    - name: Install dependencies and run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install pytest
        pytest test_app.py  # ✅ All in one step so virtual env stays active

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/flask-ec2-app
          source venv/bin/activate
          git pull origin main
          pip install -r requirements.txt
          sudo systemctl restart gunicorn

        
       
          
         
          
        

