name: Flask CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  test-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # You can customize this with your actual tests
          echo "No tests configured"

      - name: Deploy to EC2
        if: success()
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/flask-ec2-app"

      - name: Restart Flask App on EC2
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'python3 app.py' || true
            nohup python3 /home/ec2-user/flask-ec2-app/app.py > /dev/null 2>&1 &

